repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)
      - id: trailing-whitespace
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)
      - id: check-yaml
      - id: check-ast
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: detect-private-key

  - repo: local
    hooks:
      - id: block-dotenv
        name: block committing .env files
        entry: "ERROR: .env files must not be committed"
        language: fail
        files: '^\.env(|\..*)$'
        exclude: '^\.env\.example$'
