repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0   # ← ajustado
    hooks:
      - id: end-of-file-fixer
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)
      - id: trailing-whitespace
        exclude: ^(data/|\.venv/|.*\.(csv|zip|gz|tar)$)
      - id: check-yaml
      - id: check-ast

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1   # ← ajustado
    hooks:
      - id: mypy
        files: ^src/
        exclude: ^(data/|\.venv/)
