name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ─────────────────────────────────────────────────────────────────────────────
      # Requisito del repo: declara este bloque en .pre-commit-config.yaml
      #
      # - repo: local
      #   hooks:
      #     - id: spdx-header-python
      #       name: Ensure SPDX header in Python files
      #       entry: python scripts/check_spdx.py
      #       language: system
      #       files: \.py$
      # ─────────────────────────────────────────────────────────────────────────────

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Verify SPDX local hook & script presence
        run: |
          set -euo pipefail
          if [ ! -f ".pre-commit-config.yaml" ]; then
            echo "::error file=.pre-commit-config.yaml,title=Missing config::No se encontró .pre-commit-config.yaml en la raíz del repo."
            exit 1
          fi

          if ! grep -qE '^\s*-+\s*repo:\s*local\s*$' .pre-commit-config.yaml || \
             ! grep -qE '^\s*-+\s*id:\s*spdx-header-python\s*$' .pre-commit-config.yaml; then
            echo "::error title=Missing hook::Falta el hook local 'spdx-header-python' en .pre-commit-config.yaml."
            echo "Añade este bloque:"
            echo ""
            echo "- repo: local"
            echo "  hooks:"
            echo "    - id: spdx-header-python"
            echo "      name: Ensure SPDX header in Python files"
            echo "      entry: python scripts/check_spdx.py"
            echo "      language: system"
            echo "      files: \.py$"
            exit 1
          fi

          if [ ! -f "scripts/check_spdx.py" ]; then
            echo "::error title=Missing script::No existe 'scripts/check_spdx.py' requerido por el hook."
            exit 1
          fi

      - name: Run pre-commit on all files
        run: pre-commit run --all-files

      # ⬇️ Paso añadido: ejecutar también los hooks marcados con stages: [pre-push]
      - name: Run pre-commit (push stage)
        run: pre-commit run --hook-stage push --all-files
